upgrade the dependent version of ecto
dockyard/valid_field pull request #25
Opened 2017-01-17 14:54 UTC by sbatson5

Upgrade our dependent version of ecto.

2017-01-17 15:18 UTC, sbatson5 commented on test/valid_field_test.exs
> +    assert_raise ValidField.ValidationError, "Expected the following values to be invalid for \"date_of_birth\": #Ecto.Date<#{get_current_date}>", fn ->
@BlakeWilliams 👋 
I was looking at https://github.com/DockYard/valid_field/pull/21/files and wasn't sure why I had to make this change to get the tests to pass.

2017-01-17 15:44 UTC, bcardarella commented on test/valid_field_test.exs
> +    assert_raise ValidField.ValidationError, "Expected the following values to be invalid for \"date_of_birth\": #Ecto.Date<#{get_current_date}>", fn ->
time based testing is a PITA

2017-01-17 15:55 UTC, bcardarella requested changes

2017-01-17 15:55 UTC, bcardarella commented on mix.exs
> +      {:ecto, "~> 2.1.2", only: [:dev, :test]},
can you change this to `~> 2.1`

2017-01-17 15:55 UTC, bcardarella commented on test/support/model.ex
> +    |> cast(params, [:first_name, :last_name, :title, :password, :password_confirmation, :date_of_birth])
why this change?

2017-01-17 15:55 UTC, bcardarella commented on test/valid_field_test.exs
> +    assert_raise ValidField.ValidationError, "Expected the following values to be invalid for \"date_of_birth\": #Ecto.Date<#{get_current_date}>", fn ->
if `get_current_date/0` is not being used elsewhere you should just interpolate on `Ecto.Date.utc()`

2017-01-17 15:55 UTC, bcardarella commented on test/valid_field_test.exs
> +    assert_raise ValidField.ValidationError, "Expected the following values to be invalid for \"date_of_birth\": #Ecto.Date<#{get_current_date}>", fn ->
FWIW, the longer-term fix is to disassociate the datetime functionality into something that can be stubbed

2017-01-17 15:57 UTC, sbatson5 commented on test/support/model.ex
> +    |> cast(params, [:first_name, :last_name, :title, :password, :password_confirmation, :date_of_birth])
`cast/4` is being deprecated in favor of `cast/3` with `validate_required`.  Our required fields should be listed in `validate_required`

2017-01-17 16:38 UTC, sbatson5 commented on test/support/model.ex
> +    |> cast(params, [:first_name, :last_name, :title, :password, :password_confirmation, :date_of_birth])
We could still list the fields above: `@fields w(first_name, last_name, title ...)a` but this is the convention I've seen more often.

2017-01-17 18:46 UTC, brzpegasus commented on test/support/model.ex
> +    |> cast(params, [:first_name, :last_name, :title, :password, :password_confirmation, :date_of_birth])
That explains what I saw on Mike North's changeset prezo last week.

2017-01-23 15:28 UTC, sbatson5 commented on test/support/model.ex
> +    |> cast(params, [:first_name, :last_name, :title, :password, :password_confirmation, :date_of_birth])
Are we happy to mark this as resolved?

2017-03-24 14:45 UTC, bcardarella approved these changes

2017-03-24 15:23 UTC, merged